image: docker

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  BUILD_ARCH: "x86_64"
  REGISTRY_IMAGE: $CI_REGISTRY_IMAGE/$CI_PROJECT_NAME-$BUILD_ARCH

stages:
  - build

build_job:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.steventaylor.me
    - docker build --build-arg CI_JOB_AUTH='gitlab-ci-token:$CI_JOB_TOKEN' -t $REGISTRY_IMAGE:$CI_COMMIT_SHA -t $REGISTRY_IMAGE:latest -f Dockerfile.$BUILD_ARCH .
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $REGISTRY_IMAGE:latest
    - docker logout docker.steventaylor.me
