FROM mhart/alpine-node:latest

#bash is used to run npm test inside the container
RUN apk update && apk upgrade && apk --update add bash && rm -rf /var/cache/apk/*
RUN apk add --update go git

WORKDIR /src
ADD . .

ARG CI_JOB_AUTH

RUN git config --global url.http://${CI_JOB_AUTH}@gitlab.steventaylor.me/.insteadOf http://gitlab.steventaylor.me/
RUN npm install

EXPOSE 5000
CMD ["node", "app.js"]