FROM mhart/alpine-node:latest

#bash is used to run npm test inside the container
RUN apk update && apk upgrade && apk --update add bash && rm -rf /var/cache/apk/*
RUN apk add --update go git

WORKDIR /src
ADD . .

RUN if $CI_JOB_AUTH -neq ""; then git config --global url.https://$CI_JOB_AUTH@gitlab.steventaylor.me/.insteadOf https://gitlab.steventaylor.me/; fi
RUN npm install

EXPOSE 5000
CMD ["node", "app.js"]