apiVersion: v1
kind: Service
metadata:
  name: sentinel-auth
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: auth
    context: sentinel
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
        version: v1
    spec:
      containers:
        -
          name: sentinel-auth
          image: docker.io/hashneo/sentinel-auth-x86_64:latest
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "5000"
          - name: CONSUL
            value: "consul"
          - name: NEW_RELIC_ENABLED
            value: false
          - name: NEW_RELIC_APP_NAME
            value: 'Sentinel Authentication'
          - name: NEW_RELIC_LICENSE_KEY
            value: ''
          ports:
            -
              containerPort: 5000
              protocol: TCP
      nodeSelector:
          beta.kubernetes.io/arch: amd64