version: 2
jobs:
  build:
    machine: true
    context: global
    steps:
    - checkout
    - run:
        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

    # build the application image
    - run:
        docker build -t $DOCKER_ORG/sentinel-auth-x86_64:$CIRCLE_SHA1 -t $DOCKER_ORG/sentinel-auth-x86_64:latest . -f Dockerfile.x86_64

    # deploy the image
    - run: |
        docker push $DOCKER_ORG/sentinel-auth-x86_64:$CIRCLE_SHA1 &&
        docker push $DOCKER_ORG/sentinel-auth-x86_64:latest

workflows:
  version: 2
  build-deploy:
    jobs:
    - build:
        context: global