apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        context: sentinel
        version: v1
    spec:
      containers:
        -
          name: app
          image: docker.io/hashneo/sentinel-auth-x86_64:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5000"
            - name: CONSUL
              value: "consul-headless.consul.svc.cluster.local"
            - name: REDIS
              value: "redis-headless.redis.svc.cluster.local"
            - name: NEW_RELIC_ENABLED
              value: "false"
          ports:
            -
              containerPort: 5000
              protocol: TCP
      nodeSelector:
        kubernetes.io/arch: amd64
